In [2]:
import streamlit as st
import pandas as pd

2023-01-05 07:17:34.215 INFO    numexpr.utils: NumExpr defaulting to 8 threads.

In [4]:
df = pd.read_excel(r'C:\Users\muarrikh.yazka\Portfolio\Dataset\Chat_Team_CaseStudy FINAL.xlsx')

In [5]:
df.head()

,Transaction Start Date,Agent,Chat Duration,Teams,Session Name,Chat Closed By,Interactive Chat,Browser,Operating System,Geo,Response Time of Agent,Response time of Visitor,Transaction End Date,Customer Rating,Customer Comment,Transferred Chat,Customer Wait Time,Text
0,2018-06-08 23:59:00,Zaha,00:18:22,Mobile Service Team,Session:2057187615:23360,Customer,True,Edge 16.16299,Windows-10,Sweden,00:01:02,00:00:43,2018-07-08 00:18:00,,,False,00:00:01,I would really like to know the criteria which...
1,2018-06-08 23:59:00,Berenice,00:03:05,Mobile Technical Team,Session:2057187614:23368,Representative,False,Edge,Windows,Australia,00:00:00,00:00:00,2018-07-08 00:02:00,,,True,00:01:01,NaN
2,2018-06-08 23:59:00,Madi,00:22:33,Mobile Service Team,Session:2057187615:23358,Customer,True,c~67.0.3396.87,Android-4.3,Australia,00:00:32,00:01:28,2018-07-08 00:26:00,,,False,00:00:01,NaN
3,2018-06-08 23:59:00,Rose,00:38:20,Mobile Service Team,Session:2057187616:18361,System,True,Other,11.4.1,NaN,00:00:37,00:01:18,2018-07-08 00:38:00,,,False,00:00:01,Just wondered which airline would give any so...
4,2018-06-08 23:59:00,Sarrah,00:11:50,Fixed Service Team,Session:2057187617:2598,Representative,True,Other,Android 8.1.0,NaN,00:00:21,00:00:38,2018-07-08 00:14:00,,,False,00:00:01,Do they offer lunch or should we eat outside?

In [8]:
df[['Session Name']].groupby('Session Name').count()

Empty DataFrame
Columns: []
Index: [Session:2057187614:10011, Session:2057187614:10016, Session:2057187614:10098, Session:2057187614:10110, Session:2057187614:10143, Session:2057187614:10174, Session:2057187614:10220, Session:2057187614:10259, Session:2057187614:10272, Session:2057187614:10290, Session:2057187614:10321, Session:2057187614:10492, Session:2057187614:10503, Session:2057187614:10511, Session:2057187614:10516, Session:2057187614:10527, Session:2057187614:10539, Session:2057187614:10563, Session:2057187614:10614, Session:2057187614:10619, Session:2057187614:10638, Session:2057187614:10644, Session:2057187614:10668, Session:2057187614:10731, Session:2057187614:10769, Session:2057187614:10829, Session:2057187614:11048, Session:2057187614:11055, Session:2057187614:11061, Session:2057187614:11143, Session:2057187614:11191, Session:2057187614:11204, Session:2057187614:11255, Session:2057187614:11276, Session:2057187614:11297, Session:2057187614:11300, Session:2057187614:11311, Session:2057187614:11344, Session:2057187614:11354, Session:2057187614:11367, Session:2057187614:11369, Session:2057187614:11371, Session:2057187614:11420, Session:2057187614:11448, Session:2057187614:11458, Session:2057187614:11479, Session:2057187614:11483, Session:2057187614:11485, Session:2057187614:11491, Session:2057187614:11503, Session:2057187614:11521, Session:2057187614:11524, Session:2057187614:11535, Session:2057187614:11550, Session:2057187614:11583, Session:2057187614:11608, Session:2057187614:11616, Session:2057187614:11626, Session:2057187614:11633, Session:2057187614:11641, Session:2057187614:11653, Session:2057187614:11665, Session:2057187614:11680, Session:2057187614:11750, Session:2057187614:11761, Session:2057187614:11775, Session:2057187614:11776, Session:2057187614:11780, Session:2057187614:11786, Session:2057187614:11796, Session:2057187614:11800, Session:2057187614:11802, Session:2057187614:11836, Session:2057187614:11845, Session:2057187614:11939, Session:2057187614:11940, Session:2057187614:11948, Session:2057187614:11959, Session:2057187614:11963, Session:2057187614:11972, Session:2057187614:12013, Session:2057187614:12030, Session:2057187614:12035, Session:2057187614:12042, Session:2057187614:12051, Session:2057187614:12055, Session:2057187614:12076, Session:2057187614:12088, Session:2057187614:12099, Session:2057187614:12102, Session:2057187614:12111, Session:2057187614:12135, Session:2057187614:12137, Session:2057187614:12140, Session:2057187614:12147, Session:2057187614:12160, Session:2057187614:12174, Session:2057187614:12179, Session:2057187614:12182, Session:2057187614:12190, ...]

[31952 rows x 0 columns]